# Space专用训练配置文件
# 针对Hugging Face Spaces环境优化

model:
  name: "google/gemma-3-1b-it"
  max_length: 1024  # 减少序列长度以节省显存
  use_4bit: true
  use_nested_quant: true
  bnb_4bit_compute_dtype: "bfloat16"

dataset:
  name: "shawhin/tool-use-finetuning"
  train_split: "train"
  validation_split: "validation"
  max_samples: 100  # 限制样本数量以节省时间

lora:
  r: 8  # 减少rank以节省显存
  lora_alpha: 16
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

training:
  output_dir: "./outputs"
  num_train_epochs: 1  # 减少训练轮数
  per_device_train_batch_size: 2  # 减少batch size
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_steps: 10  # 减少warmup步数
  logging_steps: 5
  eval_steps: 20
  save_steps: 50
  save_total_limit: 2
  evaluation_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  fp16: true
  dataloader_pin_memory: false
  remove_unused_columns: false
  push_to_hub: false
  report_to: "none"  # 禁用wandb以节省资源

data_processing:
  max_seq_length: 1024  # 减少序列长度
  text_column: "text"
  remove_columns: ["id", "conversations"]
  template_format: "tool_use"
