# GTX 1080优化训练配置文件
model:
  name: "google/gemma-3-1b-it"
  max_length: 1024  # 减少序列长度以适应8GB显存
  use_4bit: true
  use_nested_quant: true
  bnb_4bit_compute_dtype: "bfloat16"

dataset:
  name: "shawhin/tool-use-finetuning"
  train_split: "train"
  validation_split: "validation"
  max_samples: 200  # 限制数据集大小以适应显存

lora:
  r: 8  # 减少LoRA rank以节省显存
  lora_alpha: 16
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]  # 减少目标模块

training:
  output_dir: "./outputs"
  num_train_epochs: 2  # 减少训练轮数
  per_device_train_batch_size: 1  # GTX 1080使用batch size 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 16  # 增加梯度累积以保持有效batch size
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_steps: 50
  logging_steps: 5
  eval_steps: 50
  save_steps: 200
  save_total_limit: 2
  evaluation_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  fp16: true
  dataloader_pin_memory: false
  remove_unused_columns: false
  push_to_hub: false
  report_to: "wandb"
  # GTX 1080优化设置
  dataloader_num_workers: 1  # 减少worker数量
  gradient_checkpointing: true
  optim: "paged_adamw_8bit"
  lr_scheduler_type: "cosine"
  # 内存优化
  max_grad_norm: 0.3
  warmup_ratio: 0.1

data_processing:
  max_seq_length: 1024  # 减少序列长度
  text_column: "text"
  remove_columns: ["query_type", "num_tools_available", "tool_needed", "tool_name"]
  template_format: "tool_use"
