# 使用公开可用模型的训练配置
# 用于测试和开发

model:
  name: "microsoft/DialoGPT-small"  # 公开可用的对话模型
  max_length: 1024
  use_4bit: false  # 禁用量化以提高兼容性
  use_nested_quant: false
  bnb_4bit_compute_dtype: "bfloat16"

dataset:
  name: "shawhin/tool-use-finetuning"
  train_split: "train"
  validation_split: "validation"
  max_samples: 100  # 限制数据集大小用于测试

lora:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules: ["c_attn", "c_proj"]  # DialoGPT特定模块

training:
  output_dir: "./outputs"
  num_train_epochs: 1  # 仅用于测试
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 2
  learning_rate: 1e-4
  weight_decay: 0.01
  warmup_steps: 10
  logging_steps: 5
  eval_steps: 50
  save_steps: 50
  save_total_limit: 1
  eval_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  fp16: false  # 禁用fp16以提高兼容性
  dataloader_pin_memory: false
  push_to_hub: false
  report_to: "none"  # 禁用wandb

data_processing:
  max_seq_length: 512
  remove_columns: []