# 优化训练配置文件
# 基于第一性原理优化的参数配置

model:
  name: "google/gemma-3-1b-it"
  max_length: 2048
  use_4bit: true
  use_nested_quant: true
  bnb_4bit_compute_dtype: "bfloat16"

dataset:
  name: "shawhin/tool-use-finetuning"
  train_split: "train"
  validation_split: "validation"
  max_samples: 1000  # 限制数据集大小以提高训练效率

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

training:
  output_dir: "./outputs"
  num_train_epochs: 2  # 减少训练轮数
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 1e-4  # 降低学习率
  weight_decay: 0.01
  warmup_steps: 50  # 减少预热步数
  logging_steps: 20  # 增加日志间隔
  eval_steps: 200  # 增加评估间隔
  save_steps: 200  # 修复：使其等于eval_steps
  save_total_limit: 2  # 减少保存的检查点数量
  eval_strategy: "steps"  # 修复参数名
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  fp16: true
  dataloader_pin_memory: true  # 启用内存固定
  push_to_hub: false
  report_to: "wandb"

data_processing:
  max_seq_length: 1024  # 减少序列长度以提高效率
  remove_columns: []  # 暂时不移除任何列，让代码自动处理
