# Windows CUDA环境训练配置文件
model:
  name: "google/gemma-3-1b-it"
  max_length: 2048
  use_4bit: true
  use_nested_quant: true
  bnb_4bit_compute_dtype: "bfloat16"

dataset:
  name: "shawhin/tool-use-finetuning"
  train_split: "train"
  validation_split: "validation"
  max_samples: null  # null表示使用全部数据

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

training:
  output_dir: "./outputs"
  num_train_epochs: 3
  per_device_train_batch_size: 2  # Windows上使用较小的batch size
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 8  # 增加梯度累积步数
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_steps: 100
  logging_steps: 10
  eval_steps: 100
  save_steps: 500
  save_total_limit: 3
  evaluation_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  fp16: true
  dataloader_pin_memory: false
  remove_unused_columns: false
  push_to_hub: false
  report_to: "wandb"
  # Windows优化设置
  dataloader_num_workers: 2  # Windows上减少worker数量
  gradient_checkpointing: true
  optim: "paged_adamw_8bit"
  lr_scheduler_type: "cosine"

data_processing:
  max_seq_length: 2048
  text_column: "text"
  remove_columns: ["id", "conversations"]
  template_format: "tool_use"
